# AnthorOS Catalyst configuration
storedir = /var/tmp/catalyst
jobs = 2
load-average = 2.0

# Each option on its own line as a list item
options =
    autoresume
    bindist
    kerncache
    pkgcache
    seedcache
